In [1]:
import numpy as np

## DataTypes & Attributes 

In [7]:
# NumPy's main datatype is ndarray...n-dimension array
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [8]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a2.shape

(2, 3)

In [9]:
a1.ndim, a2.ndim

(1, 2)

In [10]:
a1.dtype, a2.dtype

(dtype('int32'), dtype('float64'))

In [14]:
a1.size,a2.size

(3, 6)

In [16]:
type(a1), type(a2)


numpy.ndarray

In [17]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating NumPy arrays 

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int32')

In [22]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
ones.dtype

dtype('float64')

In [24]:
type(ones)

numpy.ndarray

In [29]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])